#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 31 16:44:20 2022

@author: qian.cao
"""

import numpy as np
import matplotlib.pyplot as plt
import nrrd
import glob

# read one of the grayscale roi files (replace the path with your own folder)
ind = 0
roi_dir = "/gpfs_projects/qian.cao/sriharsha.marupudi/extract_rois_output_grayscale/"

img_fns = glob.glob(roi_dir+"*.nrrd")
img, header = nrrd.read(img_fns[0])

# mock thresholding
threshold = 5e3
th = img > threshold

# display
fig = plt.figure()
plt.imshow(img[:,:,150],cmap="gray")
plt.contour(th[:,:,150],level=0.5,linewidths=0.5)
plt.axis("off")

