#$ -S /bin/sh
#$ -cwd
#$ -j y
#$ -N MESHING
#$ -P CDRHID0018
#$ -o /home/qian.cao/sysout
#$ -l h_rt=60:00:00     # time limit
#$ -l h_vmem=16G       # memory limit
#$ -pe thread 8
#$ -t 1-168
#$ -l gpus=0

source /home/qian.cao/.bashrc
time python ./test_20220603_FEA_linear_partial_driver_L1.py $SGE_TASK_ID

# Information on Grid Engine: 
# http://gridscheduler.sourceforge.net/htmlman/manuals.html
# https://info.hpc.sussex.ac.uk/hpc-guide/how-to/array.html
# -m mail
# -o location of output files
# -l gpus=1 (per node, I think) gpu=0 to make the script run on a gpu node while not occupying any gpus
# -l sm01 opa are "good machines" -Mike